#            predicting home price in monroe, new jersey (USA) :-

Below is the table containing home prices in monroe twp, NJ. Here price depends on area (square feet), bed rooms and age of the home (in years). Given these prices we have to predict prices of new homes based on area, bed rooms and age.

Given these home prices find out price of a home that has :-

3000 sqr ft area, 3 bedrooms, 40 year old

2500 sqr ft area, 4 bedrooms, 5 year old

We will use regression with multiple variables here. Price can be calculated using following equation,

In [1]:
import numpy as pd
import pandas as pd

In [2]:
df = pd.read_csv('D:\_practice_data\\multiple_linear_2.csv')

In [3]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [10]:
# checking the null value
df['bedrooms'].isnull().sum()

1

In [11]:
# calculating the median
df.bedrooms.median()

3.5

In [12]:
# converting to integer
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

3

In [17]:
# filling the null values through median
df.bedrooms.fillna(median_bedrooms)

0    3.0
1    4.0
2    3.0
3    3.0
4    5.0
Name: bedrooms, dtype: float64

In [19]:
# clean the data set
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [23]:
# importing the model
from sklearn import linear_model

In [27]:
# fitting the independent features and dependent variable
model = linear_model.LinearRegression()
model.fit(df[['area', 'bedrooms', 'age']], df.price)

LinearRegression()

In [28]:
# checking coefficient
model.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [29]:
# checking the intercept
model.intercept_

383725.0

# 3000 sqr ft area, 3 bedrooms, 40 year old

In [41]:
# predicting the 3000 sqr fit
model.predict([[3000,3,40]])

C:\Users\Kavya\anaconda3\lib\site-packages\sklearn\base.py:441: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([444400.])

In [34]:
# checking through statistically
137.25*3000+-26025*3+-6825*40+383725.0

444400.0

# 2500 sqr ft area, 4 bedrooms, 5 year old

In [42]:
# predicting the 2500 sqr fit
model.predict([[2500,4,5]])

C:\Users\Kavya\anaconda3\lib\site-packages\sklearn\base.py:441: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([588625.])

In [43]:
# checking coefficient
model.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [44]:
# checking the intercept
model.intercept_

383725.0

In [45]:
# checking through statistically
137.25*2500+-26025*4+-6825*5+383725.0

588625.0